/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/form/Button.vue')['default']
    copy: typeof import('./src/components/ThemeSwitcher copy.vue')['default']
    EmailInput: typeof import('./src/components/form/EmailInput.vue')['default']
    Form: typeof import('./src/components/form/Form.vue')['default']
    Input: typeof import('./src/components/form/Input.vue')['default']
    PasswordInput: typeof import('./src/components/form/PasswordInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInForm: typeof import('./src/components/SignInForm.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
  }
}
